class_name LevelData
extends Resource

## Index in the Global Arena Array
@export var level_id: int
## Displayed name of the level
@export var level_name: String
## True if the level has the unlocked by something
@export var is_locked := false
## Current completion state of the level
@export var is_completed := false
## True if the level has been completed in the past
@export var has_been_completed := false


## Global start position of the level, it is set by the StartPoint Node3D inside each level scene.
var start_position: Vector3
## Is generated by the child count of the levels Enemies Node
var enemy_count: int
## The current count of flashed enemies
var enemies_flashed_count: int

## The "high score" of the level
var enemies_flashed_count_best: int
